-- Phase 7 — intentionally empty.
--
-- Supabase's current guidance advises against using `supabase db push
-- --include-seed` against a real/production project — seed data is meant
-- for local/preview development only. The legitimate initial platform
-- records (the Kameleon client and its draft experience) were moved out
-- of this file into a tracked migration instead:
--   supabase/migrations/20260804200621_initial_client_records.sql
-- That migration is applied the same way as the rest of the schema
-- (`supabase db push`, no --include-seed flag), so it runs exactly once,
-- idempotently, against every environment including the linked
-- "The Retail Experience" project — never through this file.
--
-- Do NOT run this file (or `db push --include-seed`) against the linked
-- remote project. If disposable local/preview-only fixture data is ever
-- needed for development (e.g. throwaway test tenants), it belongs here —
-- explicitly labeled as disposable, never real client data, and never
-- referenced by any tracked migration.
